const dame = {
  pièce: {
    type: 'dame',
    blanche: '&#9813;',
    noire: '&#9819;',
    quantitéIntiale: 1,
    positionInitiale: {
      blanche: ["d1"],
      noire: ["d8"]
    }
  },
  mouvements: [
    { haut: 1, droite: 1 },
    { haut: 2, droite: 2 },
    { haut: 3, droite: 3 },
    { haut: 4, droite: 4 },
    { haut: 5, droite: 5 },
    { haut: 6, droite: 6 },
    { haut: 7, droite: 7 },
    { haut: 1, gauche: 1 },
    { haut: 2, gauche: 2 },
    { haut: 3, gauche: 3 },
    { haut: 4, gauche: 4 },
    { haut: 5, gauche: 5 },
    { haut: 6, gauche: 6 },
    { haut: 7, gauche: 7 },
    { bas: 1, droite: 1 },
    { bas: 2, droite: 2 },
    { bas: 3, droite: 3 },
    { bas: 4, droite: 4 },
    { bas: 5, droite: 5 },
    { bas: 6, droite: 6 },
    { bas: 7, droite: 7 },
    { bas: 1, gauche: 1 },
    { bas: 2, gauche: 2 },
    { bas: 3, gauche: 3 },
    { bas: 4, gauche: 4 },
    { bas: 5, gauche: 5 },
    { bas: 6, gauche: 6 },
    { bas: 7, gauche: 7 },
    { haut: 1, droite: 0 },
    { haut: 2, droite: 0 },
    { haut: 3, droite: 0 },
    { haut: 4, droite: 0 },
    { haut: 5, droite: 0 },
    { haut: 6, droite: 0 },
    { haut: 7, droite: 0 },
    { bas: 1, droite: 0 },
    { bas: 2, droite: 0 },
    { bas: 3, droite: 0 },
    { bas: 4, droite: 0 },
    { bas: 5, droite: 0 },
    { bas: 6, droite: 0 },
    { bas: 7, droite: 0 },
    { haut: 0, droite: 1 },
    { haut: 0, droite: 2 },
    { haut: 0, droite: 3 },
    { haut: 0, droite: 4 },
    { haut: 0, droite: 5 },
    { haut: 0, droite: 6 },
    { haut: 0, droite: 7 },
    { bas: 0, gauche: 1 },
    { bas: 0, gauche: 2 },
    { bas: 0, gauche: 3 },
    { bas: 0, gauche: 4 },
    { bas: 0, gauche: 5 },
    { bas: 0, gauche: 6 },
    { bas: 0, gauche: 7 }
  ]
}

export default dame;